export default function TermsAndConditions() {
    return (
        <div className="bg-[#0A130E] min-h-screen p-6">
            <div className="max-w-7xl mx-auto">
            <h1 className="text-3xl font-bold mb-6">Terms and Conditions</h1>
            <p className="text-sm text-gray-500 mb-8">Effective Date: April 3, 2025</p>

            <p className="mb-4 text-slate-100">
                Welcome to <strong>Jamerator</strong> (the “App”), a mobile application developed by <strong>Sauce
                Studios, LLC</strong> that generates random chord progressions to assist guitar players with
                songwriting, practice, and creative inspiration.
            </p>

            <p className="mb-6">
                Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the App.
                These Terms apply to all users of the App. By accessing or using Jamerator, you agree to be bound by
                these Terms. If you do not agree with any part of the Terms, you may not access or use the App.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-100">1. Use of the App</h2>
            <p className="mb-4 text-slate-100">
                You agree to use Jamerator only for lawful purposes and in compliance with these Terms. The App is
                intended for users aged 13 and older. If you are under the age of 18, you must use the App with the
                involvement of a parent or legal guardian.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-100">2. Intellectual Property</h2>
            <p className="mb-4 text-slate-100">
                All content, features, and functionality within Jamerator, including but not limited to design, text,
                graphics, logos, and software, are the exclusive property of <strong>Sauce Studios, LLC</strong> and are
                protected by applicable intellectual property laws. All rights are reserved.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-100">3. License</h2>
            <p className="mb-4 text-slate-100">
                We grant you a limited, non-exclusive, non-transferable, and revocable license to download, install, and
                use the App for your personal, non-commercial use, in accordance with these Terms.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-100">4. User Content</h2>
            <p className="mb-4 text-slate-100">
                If the App enables saving or sharing of chord progressions or other user-generated content, you retain
                ownership of that content. By using the App, you grant <strong>Sauce Studios, LLC</strong> a
                non-exclusive, royalty-free license to use, store, display, and process such content solely for the
                purpose of operating and improving the App.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-100">5. In-App Purchases and Subscriptions</h2>
            <p className="mb-4 text-slate-100">
                Some features of Jamerator may be available via in-app purchases or subscriptions, which are processed
                and managed through Apple’s App Store. Please refer to Apple’s terms of service and privacy policy for
                details on payment processing, renewals, and cancellations.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-100">6. Termination</h2>
            <p className="mb-4 text-slate-100">
                We reserve the right to suspend or terminate your access to the App at any time and without prior
                notice, for conduct that we believe violates these Terms or is harmful to other users, our business, or
                third parties.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-100">7. Disclaimer</h2>
            <p className="mb-4 text-slate-100">
                Jamerator is provided on an “as is” and “as available” basis without warranties of any kind, either
                express or implied. While we strive to ensure accuracy and musical usefulness, chord progressions
                generated by the App are for informational and creative use only. We make no guarantees as to their
                musical theory correctness or compatibility.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-100">8. Limitation of Liability</h2>
            <p className="mb-4 text-slate-100">
                To the maximum extent permitted by applicable law, <strong>Sauce Studios, LLC</strong> shall not be
                liable for any indirect, incidental, consequential, or special damages arising out of or in connection
                with your use of the App. This includes, but is not limited to, loss of data, lost profits, or other
                intangible losses.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-100">9. Changes to Terms</h2>
            <p className="mb-4 text-slate-100">
                We may revise these Terms from time to time. The updated version will be posted within the App or on our
                official website, with the updated effective date. Continued use of the App after such changes
                constitutes acceptance of the new Terms.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-100">10. Governing Law</h2>
            <p className="mb-4 text-slate-100">
                These Terms shall be governed and interpreted in accordance with the laws of the State
                of <strong>Tennessee</strong>, United States, without regard to its conflict of law provisions.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-4 text-slate-100">11. Contact Us</h2>
            <p className="mb-1">If you have any questions or concerns about these Terms and Conditions, please contact
                us at:</p>
            <p className="mb-1"><a href="mailto:support@saucestudios.io"
                                     className="text-green-500 hover:underline">support@saucestudios.io</a></p>
            <p><a href="https://jamerator.app" className="text-green-500 hover:underline">https://www.jamerator.app</a></p>
            </div>
        </div>

    )
}